#!/bin/sh
# Print additional version information for non-release trees.

usage() {
	echo "Usage: $0 [srctree]" >&2
	exit 1
}

cd "${1:-.}" || usage

# Check for any localversion-* files
printf '%s' "`cat localversion-* 2>/dev/null`"
